# Generated by Django 4.0 on 2025-02-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=16, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='説明文')),
                ('category', models.CharField(choices=[('sum', 'サマナーズウォー'), ('valorant', 'ヴァロラント'), ('chat', '雑談'), ('csgo', 'csgo'), ('minecraft', 'マインクラフト'), ('gtv', 'グランドセフトオートV'), ('fortnite', 'フォートナイト'), ('among us', 'アモングアス'), ('st5', 'ストリートファイター６'), ('apex', 'エイペックス')], max_length=50, verbose_name='ゲームタグ')),
                ('movie', models.FileField(upload_to='videos/', verbose_name='動画ファイル')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to='accounts.customuser')),
                ('subscribing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_message', models.CharField(max_length=100, verbose_name='ステータスメッセージ')),
                ('icon', models.ImageField(upload_to='Twitchapp', verbose_name='アイコン')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to='accounts.customuser')),
                ('Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント内容')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Twitchapp.twitchpost')),
            ],
        ),
    ]
