# Generated by Django 4.0 on 2024-11-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='チャンネル名')),
                ('content', models.TextField(verbose_name='説明文')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='動画')),
                ('category', models.CharField(choices=[('chat', '雑談'), ('japanese', '日本語'), ('english', '英語'), ('korean', '韓国語'), ('katojunichi', '加藤純一'), ('hamakawahikaru', '濱川希星'), ('game', 'ゲーム')], max_length=50, verbose_name='ハッシュタグ')),
            ],
        ),
    ]
