# Generated by Django 4.0 on 2024-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=16, verbose_name='チャンネル名')),
                ('channel_number', models.IntegerField(verbose_name='チャンネル番号')),
                ('content', models.TextField(verbose_name='説明文')),
                ('category', models.CharField(choices=[('valorant', 'ヴァロラント'), ('chat', '雑談'), ('summonerswar', 'サマナーズウォー'), ('fortnite', 'フォートナイト'), ('apex', 'エイペックス'), ('minecarft', 'マインクラフト')], max_length=50, verbose_name='ゲームタグ')),
                ('movie', models.FileField(max_length='100', upload_to='', verbose_name='動画ファイル')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
